### ISSUE TITLE
sudo make install does not work

### ISSUE THREAD

**Issue by stefonarch** [zjes/lxqt-appswitcher#1]
It builds fine but ends up with 
'no rule to generate  target "install"' 

[ 92%] Built target lxqt-config-appswitcher
[100%] Linking CXX executable lxqt-appswitcher
[100%] Built target lxqt-appswitcher
make: ***  Nessuna regola per generare l'obiettivo "install".  Arresto.

**Comment by zjes** [comment]
You are fast :), fixed...
