### ISSUE TITLE
Setting "Filter by desktop" excludes windows displayed on all virtual desktops from LXQt Application Swticher

### ISSUE THREAD

**Issue by pmattern** [zjes/lxqt-appswitcher#10]
When setting "Filter by desktop" is checked in `lxqt-config-appswitcher` windows that are configured to be displayed on all virtual desktops, e. g. by selecting `Send to Desktop` - `All desktops` from the context menu of windows' title bar under Openbox, are no longer covered by LXQt Application Switcher.

To some degree this may be a matter of taste. Personally, I think windows configured to be displayed on all virtual desktops should be treated on every desktop exactly the same way as windows residing on the respective desktop only. This should include setting `Filter by screen`.
The application switcher of Xfwm is behaving like that, too.

Seen running afbbb31 on Arch Linux.

**Comment by zjes** [comment]
Hi, sorry for this lo-o-o-ng delay. I have new job and have no free time :)
I'll fix it ASAP.

**Comment by zjes** [comment]
I hope it was fixed in 73ac87c.

**Comment by pmattern** [comment]
Problem is indeed fixed as of 73ac87c.
