### ISSUE TITLE
kwin not supported

### ISSUE THREAD

**Issue by stefonarch** [zjes/lxqt-appswitcher#2]
Installed  and back again ;)
With kwin  which is my favourite it does not seem to work: pops up, lists windows, cicling works and disappears as it should, but no window gets activated. It seems that my theme  frost gets chosen right, on openbox it's white instead but everything works.

Starting from comand line :

$ lxqt-appswitcher 
"ambiance"
2
2
1
...

**Comment by zjes** [comment]
hmm.... i will try kwin.
Seems that you must switch off default application switcher in openbox, in ~/.config/openbox/rc.xml
keybind key="A-Tab... just comment this binding section. (I don't know other ways how to switch it off)

**Comment by zjes** [comment]
Kwin is funny, i cannot find configuration tool... doen't matter, possible it was fixed..

**Comment by stefonarch** [comment]
Your fast too :)
It's working well now.
I like the list-layout very much.
