### ISSUE TITLE
Adding appswitcher to LXQt-weblate?

### ISSUE THREAD

**Issue by stefonarch** [zjes/lxqt-appswitcher#20]
Just came to my mind now, how about adding it here: https://translate.lxqt-project.org/projects/?
Pull request will be made  by LXQt-bot.

**Comment by zjes** [comment]
App switcher is not part of the lxqt. This is 3-rd party plugin. It would be strange to add it to official lxqt project.
But who knows :)

**Comment by stefonarch** [comment]
In our weblate platform are present  other projects too: tsujan (featherpad/kvantum) and andrew bipp (cmst), it would be under your name or whatever, not among the "ufficial" components.

**Comment by zjes** [comment]
In this case, ok. I just don't know how to do it. If can do it, please, fill free. Or explain me how I can do it. :)

**Comment by stefonarch** [comment]
https://translate.lxqt-project.org/projects/zjes/
Done, and looks like it works.
