### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by redtide** [zjes/lxqt-appswitcher#23]
I wonder why there are no tags, so that having a tarball would be possible to have an official package at least under Archlinux, instead of installing AUR stuff.

**Comment by zjes** [comment]
Nobody asked about it. :) This is **unofficial** plugin for lxqt.

**Comment by redtide** [comment]
Who cares if official or not, if it works well why not? :)

**Comment by zjes** [comment]
I created one.
I'm not experienced in release creation on github, but if this is correct, please close issue :)

**Comment by redtide** [comment]
Fine to me, thanks! I asked about this to a package maintainer, he said that a [semantic versioning](https://semver.org/#is-v123-a-semantic-version) is preferable (1.0.0 instead v1.0), the important is to keep it in the same way later on.

**Comment by redtide** [comment]
I've created an AUR [PKGBUILD] release version, but it would be nice to rename the version if possible as mentioned above, thanks.

[PKGBUILD]: https://aur.archlinux.org/packages/lxqt-appswitcher
