### ISSUE TITLE
several mixed findings

### ISSUE THREAD

**Issue by pmattern** [zjes/lxqt-appswitcher#3]
Issue meant to summarize some findings which I'd consider worth mentioning but which sure don't justify a report on their own:

The code doesn't provide any license information.
It's lacking in the actual source files' headers and a file LICENSE or COPYING in the code's source directory isn't available either.

If I'm not mistaken the tool is by default _not_ set up as "LXQt module".
This is contrasting what's written on https://github.com/zjes/lxqt-appswitcher and could e. g. be fixed by adding a file `$XDG_CONFIG_DIRS/autostart/lxqt-appswitcher.desktop` like this

```
[Desktop Entry]
Type=Application
Name=LXQt Application Switcher 
GenericName=Window Switcher
Comment=List of windows displayed while cycling by keyboard shortcut.
TryExec=lxqt-appswitcher
Exec=lxqt-appswitcher

OnlyShowIn=LXQt;
X-LXQt-Module=true
Hidden=true
```

While `Alt+Tab` was working flawlessly I didn't manage to get `Alt+Shift+Tab` to circle the other way around, no matter what I tried to set in `rc.xml` of Openbox.
Seen on Arch Linux x86_64 in a KVM/QEMU virtual machine. Artifacts due to running in a VM IMO pretty unlikely as `Alt+Shift+Tab` was working flawlessly using the genuine GUI of Openbox.

Internationalization / localization would be something nice to have in the long run.

Same thing with man pages. Just two small ones briefly describing binaries `lxqt-[config-]appswitcher` would be good.

**Comment by zjes** [comment]
Nice, thank you for this report. :) 

Please, show me those artifacts?

**Comment by pmattern** [comment]
"Artifacts" → Probably some misundertanding? Special keys may behave unexpected within a virtual machine. All I wanted to say is that this does *not* seem likely here as `Alt+Shift+Tab` was working with the GUI of Openbox but not with lxqt-appswitcher. So it's rather lxqt-appswitcher or maybe some configuration error that prevents `Alt+Shift+Tab` from working.

**Comment by zjes** [comment]
I thought about some kind of graphical artifacts. Sorry. 
Reverse switching... it's not a bug, it's just not implemented yet. :)

**Comment by zjes** [comment]
Reverse switch was added. 
Desktop file to autostart was added. 
To be continue...

**Comment by pmattern** [comment]
I can confirm `lxqt-appswitcher` is now correctly handled as LXQt module and cycling to previous windows works as well.

As little addendum I'd suggest to exchange header "Dialog" of `lxqt-config-appswitcher` with something more meaningful like "LXQt Application Switcher Configuration".
