### ISSUE TITLE
Fix some warnings

### ISSUE THREAD

**Issue by gfgit** [zjes/lxqt-appswitcher#33]
Hello, is this project still active?
I've forked it on [git.disroot.org/gfgit/lxqt-mobile-appswitcher.git](https://git.disroot.org/gfgit/lxqt-mobile-appswitcher.git)

My goal is to create a mobile friendly App switcher, similar to what is found on Android. Hopefully with touchscreen gesture recognition.
While doing that, I've found some warnings about:

- CMake include order error and hard coded Release build type
- `KWindowSystem` deprecated X11 related methods and moved to `KX11Extras`
- Use `nullptr` instead of `0`

You can find related commits fixing these issues on branch on [work/gfgit/fix_warnings](https://git.disroot.org/gfgit/lxqt-mobile-appswitcher/src/branch/work/gfgit/fix_warnings)

**Comment by gfgit** [comment]
I've made PR #34 so it's easier to merge

**Comment by stefonarch** [comment]
I'm afraid there is no sign of life here anymore, I just noticed that it's 2 years translations from LXQt weblate instance aren't merged anymore.

**Comment by zjes** [comment]
Hi,
mostly.
I don't use lxqt about long time.  But I always merge pull requests. Seems
that GitHub doesn't send me notifications about new prs. Anyway, I'm glad
that somebody still interested in it :)
