### ISSUE TITLE
Usage on virtual desktop without windows triggers crash

### ISSUE THREAD

**Issue by pmattern** [zjes/lxqt-appswitcher#6]
If lxqt-appswitcher gets used on a virtual desktop which doesn't host any windows it crashes and dumps core.

Right before the crash a little empty square can be seen at the application switcher's regular location
![lxqt-appswitcher_core-dump-no-window_square](https://cloud.githubusercontent.com/assets/9860801/13219802/960c72d0-d972-11e5-861a-7b49f2c13632.png)
Problem can be seen with KWin, Openbox and Xfwm. It doesn't matter whether compositing, Compton with Openbox or inherent compositor of KWin and Xfwm, is available.
Strack trace and backtrace after transferring the core dump to gdb via `coredumpctl` on Arch Linux x86_64 running Openbox can be found on https://gist.github.com/pmattern/9eac4f2c6c2d931b2d95.

a59993d on up to date Arch Linux x86_64 or i686, hence KWin 5.5.4, Openbox 3.6.1 and Xfwm 4.12.3.

**Comment by zjes** [comment]
Fixed in eda930d.
Thank you again for report. :)

**Comment by pmattern** [comment]
Problem can no longer be seen with eda930d and all three window managers in question.
Taking the liberty to close this issue.
