### ISSUE TITLE
lxqt-config-appswitcher: mnemonics

### ISSUE THREAD

**Issue by pmattern** [zjes/lxqt-appswitcher#7]
It would be good if the topics in `lxqt-config-appswitcher` could be selected by mnemonics / underlined letters that can be used to select the topic by hitting `Alt+<letter>`.

Working on German translation it turned out these do already work in section "Filters". All it takes is to mark the letter in question as `&<letter>` in the TS file as usual.
In section "Appearance" they don't work yet, though. Of course the situation is a bit different here as it's not about check boxes but those forms where numeric values can be filed or set by the controls at the right. But I think mnemonics make sense here as well and technically it should be feasible as can be seen in [ObConf-Qt](https://github.com/lxde/obconf-qt), Window Manager Preferences - Primary Monitor.

**Comment by zjes** [comment]
May you look to 6e5171d. It will be ok?

**Comment by pmattern** [comment]
Mnemonics are working exactly as expected now.

I just think it would be good if you updated `./config/translations/lxqt-config-appswitcher.ts` accordingly.
This would make translators consider them while translating while at the same time suppressing some unnecessary error messages of Qt Linguist which result from adding mnemonics in translations right now.

**Comment by zjes** [comment]
Yes, i decide to commit common things before *.ts. If something was wrong. :)

**Comment by pmattern** [comment]
> Yes, i decide to commit common things before *.ts. If something was wrong

That makes sense.

**Comment by zjes** [comment]
I've updated translations. But one problem, cannot solve it yet (maybe local). Strings with & not shown translated.

**Comment by pmattern** [comment]
String `&amp;` which is used to mark the mnemonics needs to be included in the translated strings as well, e. g. something like `Max &amp;položek k zobrazení`.

The TS files currently available still feature tag `type="unfinished"` besides the corresponding strings have already been translated. This ought to be fixed.
[Qt Linguist](http://doc.qt.io/qt-5/linguist-translators.html) marks errors like that and makes them easy to discover and fix, [see also](http://doc.qt.io/qt-5/qtlinguist-index.html).

To my knowledge it's common practice to add `&amp;` not in template file `*.ts` in the directories comprising the translated TS files `*_foo.ts` but primarily in the source code.
E. g. compare https://github.com/lxde/obconf-qt/blob/e21185158924856a3456400b05df066bcc7fb784/src/obconf.ui#l120 with https://github.com/lxde/obconf-qt/blob/e21185158924856a3456400b05df066bcc7fb784/src/translations/obconf-qt.ts#l82 (sure enough the wrong source code file is referenced in `obconf-qt.ts` but the concept applies nevertheless). Once included in the source code strings `&amp;` are transferred to the template TS file `*.ts` when the latter gets generated automatically by running `lupdate` or whatever. String `&amp;` has nevertheless to be added to the translated strings manually as stated above after the template TS file gets copied to the language specific files `*_foo.ts` and these get edited.
My knowledge of all that stuff is rather superficial, though.

**Comment by zjes** [comment]
Thank you. It was my error. :)

**Comment by zjes** [comment]
So, how are you with translations? It's ok? Close this issue? :)

**Comment by pmattern** [comment]
Regarding the source code and the template TS files `lxqt-appswitcher.ts` and `lxqt-config-appswitcher.ts` everything is alright as far as I can tell.
German translation proposed in #9 works as expected.
Regarding the preexisting Czech and Russian translations the problems stated in the first two paragraphs of my previous comment persist. Due to the first one mnemonics aren't available using these translations, the second one makes tools like Qt Linguist throw superfluous warnings. Your mileage may vary.

But no matter whether or not you decide to adjust those two preexisting translations this issue can now indeed be considered fixed, yes.
