### ISSUE TITLE
GUI: maximum text length and font size

### ISSUE THREAD

**Issue by pmattern** [zjes/lxqt-appswitcher#8]
It would be helpful if a maximum text length beyond 99 digits was allowed and configurable in `lxqt-config-appswitcher`.
This may not be needed too regularly. But IMO being able to display lengthy window headers in a single row is one of the main advantages of LXQt Application Switcher compared to the window managers' counterparts and a length beyond 99 digits may very well make sense at times. Also, this is only about a maximum allowed value, users would obviously still be free to use some small value which could also remain as default.

Being able to set a custom font size would provide some benefit as well.
FWIW this is already implemented in configuration dialogue "Main Menu settings" of plugin-mainmenu.

**Comment by zjes** [comment]
May you look to 6e5171d. It's will ok?

**Comment by pmattern** [comment]
As for text length everything is fine now, IMO.

As for custom font size basically as well, but I think one thing should be changed.
When a custom value was set and the check box gets unchecked the custom value is forgotten. Rather, the next time `lxqt-config-appswitcher` gets launched it will show the system's default value as seen in `lxqt-config-appearance` - Font (left pane). Apparently the correlate is an unchecked check box getting saved as font size 0 in `.config/lxqt/app-switcher.conf`.
I think it would be better if the custom font size itself (value in pt) and whether or not it is active were saved as two independent settings. This would allow for switching between the default value and a custom value that was once set easily.
That whole thing may be a matter of taste. But the behaviour I'm proposing is what dialogue "Main Menu settings" of plugin-mainmenu does so it should actually be done to be consistent.

**Comment by zjes** [comment]
Hmm... the second reason (first was new value in config) was way to show current (default) font size. No more ways to view default size, only in lxqt-appearance dialog, and i dont't like that config in main menu shows 11 pt as default, because this value is wrong. But ok, I will change this behavior.

**Comment by pmattern** [comment]
I think I get your point but nevertheless think what I proposed / the behaviour of plugin-mainmenu makes more sense.
It's of course true that *seeing* the current default value in `lxqt-config-appswitcher` would be prevented. But *using* the default value is still very easily achieved by just unchecking the check box of custom font size. And being able to re-use a custom value that had been active before matters more than being able to see the default value, IMO.

**Comment by zjes** [comment]
Fixed in f05e4e9.
Thank you.

**Comment by pmattern** [comment]
Everything like it should be now, IMO.
